apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_DATABASE
          value: blogdb
        - name: MYSQL_USER
          value: avnish
        - name: MYSQL_PASSWORD
          value: redhat
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldeployment
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
