apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-host
        - name: WORDPRESS_DB_NAME
          value: blogdb
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_password
---
apiVersion: v1
kind: Service
metadata:
  name: wpdeploy
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: wordpress
